name: prueba_radio_alpha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audio_service: ^0.18.18
  flutter:
    sdk: flutter
  flutter_ignorebatteryoptimization: ^0.0.2
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
